prefix : "&8[&aPlayer_Tracker&8]"
format : "&7Tracking: &c{target} &a({range} Blocks)"
ptrack_name: "&aCompass &7(Right Click)"
def_compass: true
gui: true

#Variable formats available :

#{name} - Name of the player
#{target} - Target of radar
#{range} - Range between player to target in blocks
#{health} - Health of player targets
#{food} - Food level of player targets
