prefix : "&8[Tracker&8]"
customrecipe : true
format : "&7Tracking: &c{target} &a({range} Blocks)"
track:
  name: "&aCompass &7(Right Click)"
gui: true
defaultcompass: true

#Custom recipe enables you to create a radar by putting compass in a crafting grid
#Available format variables:
#{name} - Name of the player
#{target} - Target of radar
#{range} - Range between player to target in blocks